name: Code Coverage Report with S3 Backend
description: Comments a pull request with the code coverage for mono repo and single repo and stores lcov files inside a s3 repository
author: "Simon Tretter, based on work of Eesh Tyagi, Marina and John Hannagan"
branding:
    icon: check-square
    color: green
inputs:
    github-token:
        description: Github token
        required: true
    monorepo-base-path:
        description: Location of your monorepo `packages` parent folder.
        required: true
    s3-config:
        description: 's3 config for lcov file storage, json encoded { credentials: { accessKeyId: "", secretAccessKey: "", }, region: "", Bucket: "repository-code-coverage" }'
        required: false
    threshold:
        description: 'minimum threshold (in %) before the action fails, default is 0.05%'
        required: false
runs:
    using: node16
    main: dist/index.js
