name: Code Coverage Report
description: Comments a pull request with the code coverage for mono repo and single repo
author: "Eesh Tyagi, Marina, John Hannagan"
branding:
    icon: check-square
    color: green
inputs:
    github-token:
        description: Github token
        required: true
    monorepo-base-path:
        description: Location of your monorepo `packages` parent folder.
        required: false
    app-name:
        description: App name to display on comment
        required: false
runs:
    using: node16
    main: dist/main.js
