name: "build-and-pack"
on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      PACKED_JS_PATH: 'dist/index.js'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Pack
        run: npm run pack
      - name: Commit new build output
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: ${{ env.PACKED_JS_PATH }}
          message: 'chore: update ${{ env.PACKED_JS_PATH }}'
          default_author: github_actions

  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
