name: PR checks

on: pull_request

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    HUSKY_SKIP_INSTALL: true

jobs:
    eslint:
        name: Code quality
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: Restore node_modules cache
              uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Install packages
              run: yarn
            - name: ESLint
              run: yarn eslint

    tests:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: Restore node_modules cache
              uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Install packages
              run: yarn
            - name: All tests
              run: yarn test
            - name: Add coverage comment
              uses: hokify/code-coverage-assistant-ts@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  monorepo-base-path: ./

    build:
        name: Check build is committed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: Restore node_modules cache
              uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Install packages
              run: yarn
            - name: Build
              run: yarn build
            - name: Ensure that the committed dist matches the build
              # See if there are any diffs in the dist file. Grep returns an error
              # when there are no changes, so we flip the output
              run: (git diff --name-only | grep dist/main.js || exit 0 && exit 1)
